### PR TITLE
Update 60-configure_gpu_driver.sh

### PR DESCRIPTION
**Pull request by survivor182ca**
Add livba to allow HW encoding instead of SW encoding in sunshine

### CODE REVIEW

**Comment by alansari** [comment]
Libva2 is already included in the dockerfile.debian, maybe check that dev/dri is passed through. In sunshine conf you can set the rendernode (128/129), if you have more than one dri device.

**Comment by survivor182ca** [comment]
It does install libva from main but not the one from sid repo.

**Comment by Josh5** [comment]
What benefits are there in the one from SID?

**Comment by Josh5** [comment]
If this is going to happen, I'd rather move all VA lib installs to the init scripts for SID support. This init script is just for the drivers, not for VA. I would class this as more a thing limped witg tools like gstreamer and ffmpeg. And i was hoping to keep these on stable.

**Pull request closed without merging**
