### PR TITLE
bump sunshine to 23.1

### PR DESCRIPTION
**Pull request by alansari**
Another test to see if github actions can build the docker with latest stable sunshine

### CODE REVIEW

**Comment by alansari** [comment]
Not sure why the debian dockerfile won't build, it successfuly builds locally anytime i try.

**Comment by WillKirkmanM** [comment]
Have you seen this `Read Only Filesystem` during local development

image

**Comment by alansari** [comment]
Closing the PR, not sure how to resolve actions

**Comment by Nold360** [comment]
seems this has been fixed with https://github.com/LizardByte/Sunshine/issues/2972

at least i can install the deb inside the container

**Comment by ReenigneArcher** [comment]
@Nold360 that PR is unlikely to change anything related to a deb package. It only affects the RPM packages generated by cpack.

**Pull request closed without merging**
