### PR TITLE
Updated versions

### PR DESCRIPTION
**Pull request by banzai200**
Updated versions for noVNC,  Websocketify and Changed sunshine to LizardByte's version

### CODE REVIEW

**Comment by Josh5** [comment]
How does this affect the audio patch for novnc?

**Comment by survivor182ca** [comment]
The container compile well but I get password problem for vnc and the other stuff when I run it. Is there something to do additionnaly when you compile the image????

**Comment by survivor182ca** [comment]
Also for amg gpu we should either : 
- point to unstable repo of buster to get mesa that is not 100 year old or
- use bookworm base image

**Comment by Josh5** [comment]
I'll be looking at rebasing to bookwarm soon. Since this is a duplicate of that other issue, I'll close this one.

**Pull request closed without merging**
